"""Add hospital_id to Appointment model

Revision ID: 5ff84c146478
Revises: e44592546a5b
Create Date: 2025-01-20 19:06:00.606263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff84c146478'
down_revision = 'e44592546a5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hospital_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'hospital', ['hospital_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('hospital_id')

    # ### end Alembic commands ###
